### ISSUE TITLE
Time representation is very inconsistent

### ISSUE THREAD

**Issue by codeyellow-bv** [CodeYellowBV/realtime#45]
![times](https://cloud.githubusercontent.com/assets/6593624/25965774/3ec82742-3689-11e7-9501-aac7127e687d.png)

24hrs notation versus AM - PM notations... that kind of messes with my brain
I prefer the 24hrs notation by the way..

**Comment by SpaceK33z** [comment]
Interesting, that is coming from your own browser settings. This is a native `time` input field. I'll see if they provide a way to change that.

**Comment by SpaceK33z** [comment]
But essentially this is correct, because the browser thinks this is your preference ;).

**Comment by codeyellow-bv** [comment]
I am also test-driving a new browser .. but not sure where I have to change the AM / PM notation on this one...

**Comment by rutger** [comment]
The native time inputs are giving us too many issues, so I'm interested in trying a package for this one: [react-datetime](/YouCanBookMe/react-datetime)

Made a branch for this: [datetime-input](/CodeYellowBV/realtime/tree/datetime-input)

**Comment by SpaceK33z** [comment]
@rutger I also worked on this for a few minutes and found react-time-input to be working nicely

**Comment by SpaceK33z** [comment]
This is mostly fixed. As a last step, discussed with @rutger, we're going to use the placeholder `13:37` when the input is empty to indicate you can enter a specific time.
